recipe_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import login_view, signup, success

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
    path("login/", login_view, name="login"),
    path("", success, name="success"),
    path("signup/", signup, name="signup"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from . import views
from .views import (AddRecipe, HomeView, Profile, RecipeDetailView,
                    RecipeListView)

app_name = "recipes"

urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("recipe/", RecipeListView.as_view(), name="recipe"),
    path("recipe/<int:pk>/", RecipeDetailView.as_view(), name="detail"),
    path("recipe/add/", AddRecipe.as_view(), name="add"),
    path("recipe/<int:recipe_id>/delete/", views.delete_recipe, name="delete_recipe"),
    path("recipe/<int:recipe_id>/edit/", views.edit_recipe, name="edit_recipe"),
    path("recipe/fav/<int:recipe_id>/", views.faved_recipe, name="faved_recipe"),
    path("profile/<slug:username>/", Profile.as_view(), name="profile"),
    path(
        "profile/<slug:username>/update/",
        views.update_profile_picture,
        name="update_profile_picture",
    ),
]

recipes/models.py
import logging

from django.conf import settings
from django.contrib.auth.models import AbstractUser, Group, Permission
# Create your models here.
from django.db import models
from django.urls import reverse


class Recipe(models.Model):
    name = models.CharField(max_length=50)
    ingredients = models.CharField(max_length=255)
    cooking_time = models.IntegerField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to="recipes", default="no_picture.jpg")

    def __str__(self):
        return f"""
        {self.name}
        Ingredients: {self.ingredients}
        Cooking Time: {self.cooking_time} minutes
        Difficulty: {self.calc_difficulty()}
        """

    def calc_difficulty(self):
        difficulty_levels = {
            "Easy": "Easy",
            "Medium": "Medium",
            "Intermediate": "Intermediate",
            "Hard": "Hard",
        }

        ingredients_list = self.ingredients.split(", ")
        num_ingredients = len(ingredients_list)

        if self.cooking_time < 10:
            if num_ingredients < 4:
                difficulty = difficulty_levels.get("Easy")
            else:
                difficulty = difficulty_levels.get("Medium")
        else:
            if num_ingredients < 4:
                difficulty = difficulty_levels.get("Intermediate")
            else:
                difficulty = difficulty_levels.get("Hard")

            # Log the difficulty level
            logging.info(f"Recipe difficulty for {self.name}: {difficulty}")

        return difficulty

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        self.ingredients = self.ingredients.title()
        super(Recipe, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={"pk": self.pk})


class CustomUser(AbstractUser):
    # Add custom fields to your user model
    pic = models.ImageField(
        upload_to="profile_pics", blank=True, null=True, default="no_picture.jpg"
    )
    bio = models.TextField(blank=True, null=True)
    fav_recipes = models.ManyToManyField(
        Recipe, blank=True, related_name="users_favorites"
    )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("recipes:profile", kwargs={"username": self.username})

recipes/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["name", "cooking_time", "pic", "ingredients"]


class RecipeSearchForm(forms.Form):
    recipe_name = forms.CharField(
        label="Recipe Name",
        max_length=100,
        required=False,
    )
    ingredients = forms.CharField(
        label="Ingredients (separated by commas)",
        max_length=100,
        required=False,
    )

recipes/views.py
import base64
from io import BytesIO

import matplotlib
import matplotlib.pyplot as plt
from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, DetailView, ListView

from .models import CustomUser, Recipe

matplotlib.use("Agg")
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import RecipeForm, RecipeSearchForm


class HomeView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = "recipes/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_recipes = Recipe.objects.all()
        if len(all_recipes) >= 5:
            random_recipes = random.sample(list(all_recipes), 5)
        else:
            random_recipes = list(all_recipes)
        context["random_suggestions"] = random_recipes
        context["MEDIA_URL"] = settings.MEDIA_URL
        return context


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = self.object
        difficulty = recipe.calc_difficulty()
        context["difficulty"] = difficulty
        context["MEDIA_URL"] = settings.MEDIA_URL
        return context


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/recipe.html"
    form = RecipeSearchForm()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_recipes = Recipe.objects.all()
        context["recipes"] = all_recipes

        # Generate the graph here
        x = [recipe.name for recipe in all_recipes]
        y = [recipe.cooking_time for recipe in all_recipes]
        chart = self.get_plot(x, y)
        context["chart"] = chart
        context["MEDIA_URL"] = settings.MEDIA_URL

        return context

    def get_plot(self, x, y):
        buffer = BytesIO()
        plt.switch_backend("AGG")
        plt.figure(figsize=(10, 5))
        plt.title("Recipe Chart")
        plt.bar(x, y)
        plt.xticks(rotation=45)
        plt.xlabel("Recipes")
        plt.ylabel("Cooking Time")
        plt.tight_layout()
        plt.savefig(buffer, format="png")
        buffer.seek(0)
        image_png = buffer.getvalue()
        graph = base64.b64encode(image_png).decode("utf-8")
        buffer.close()
        return graph

    def post(self, request, *args, **kwargs):
        form = RecipeSearchForm(self.request.POST)

        if form.is_valid():
            recipe_name = form.cleaned_data["recipe_name"]
            ingredients = form.cleaned_data["ingredients"]

            recipes = Recipe.objects.all()

            if recipe_name:
                recipes = recipes.filter(Q(name__icontains=recipe_name))

            if ingredients:
                recipes = recipes.filter(Q(ingredients__icontains=ingredients))

            if not recipe_name and not ingredients:
                recipes = Recipe.objects.all()

            context = {
                "recipes": recipes,
                "form": form,
            }

            if not recipes:
                messages.info(self.request, "No recipes found")

            # Update the graph based on the filtered recipes
            x = [recipe.name for recipe in recipes]
            y = [recipe.cooking_time for recipe in recipes]
            chart = self.get_plot(x, y)
            context["chart"] = chart

            return render(self.request, "recipes/recipe.html", context)

    def graph_view(request):
        # You can access the chart within the context here
        chart = request.context["chart"]
        return render(request, "recipes/recipe.html", {"chart": chart})


class AddRecipe(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/add_recipe.html"
    form_class = RecipeForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["MEDIA_URL"] = settings.MEDIA_URL
        return context


@login_required
def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)

    if request.user == recipe.author:
        if request.method == "POST":
            # Check for a confirmation parameter sent via POST
            if request.POST:
                recipe.delete()
                return redirect("recipes:recipe")
            else:
                return redirect("recipes:detail", pk=recipe_id)
    return redirect("recipes:recipe")


@login_required
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)

    if request.user == recipe.author:
        if request.method == "POST":
            recipe_form = RecipeForm(request.POST, instance=recipe)
            if recipe_form.is_valid():
                recipe_form.save()
                return redirect("recipes:detail", pk=recipe_id)

    return redirect("recipes:detail", pk=recipe_id)


@login_required
def faved_recipe(request, recipe_id):
    user = request.user
    recipe = get_object_or_404(Recipe, pk=recipe_id)

    if user.fav_recipes.filter(pk=recipe_id).exists():
        user.fav_recipes.remove(recipe)
        is_liked = False
    else:
        user.fav_recipes.add(recipe)
        is_liked = True

    response_data = {
        "is_liked": is_liked,
    }

    return JsonResponse(response_data)


@login_required
def update_profile_picture(request, username):
    if request.method == "POST":
        profile_pic = request.FILES["profile_pic"]
        request.user.pic = profile_pic
        request.user.save()
        print(request.FILES)
        return redirect("recipes:profile", username=request.user.username)
    else:
        return redirect("recipes:profile", username=request.user.username)


class Profile(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = "recipes/profile.html"
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        created_recipes = Recipe.objects.filter(author=user)
        context["created_recipes"] = created_recipes
        context["MEDIA_URL"] = settings.MEDIA_URL
        return context

recipes/templates/recipes/add_recipe.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TasteBuds</title>
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'styles/add_recipe.css' %}"
    />
  </head>
  <body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand navbar-light bg-light">
      <div class="navbar-brand">
        <a href="{% url 'recipes:home' %}" class="navbar-brand">
          <img src="{{ MEDIA_URL }}new-tastebuds.png" class="logo" alt="Logo" />
        </a>
      </div>

      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recipes:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recipes:recipe' %}">Recipes</a>
        </li>
      </ul>
      <ul class="navbar-nav logout">
        <div class="developer">
          <a
            href="https://jarjardinks.github.io/the-portfolio/"
            class="developer-link"
            target="_blank"
            rel="noreferer"
          >
            <img
              src="{{ MEDIA_URL }}developer_icon.gif"
              alt="developer-icon"
              class="developer-icon"
            />
          </a>
        </div>
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'recipes:profile' username=request.user.username %}"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              height="24"
              viewBox="0 -960 960 960"
              width="24"
            >
              <path
                d="M480-480q-66 0-113-47t-47-113q0-66 47-113t113-47q66 0 113 47t47 113q0 66-47 113t-113 47ZM160-160v-112q0-34 17.5-62.5T224-378q62-31 126-46.5T480-440q66 0 130 15.5T736-378q29 15 46.5 43.5T800-272v112H160Zm80-80h480v-32q0-11-5.5-20T700-306q-54-27-109-40.5T480-360q-56 0-111 13.5T260-306q-9 5-14.5 14t-5.5 20v32Zm240-320q33 0 56.5-23.5T560-640q0-33-23.5-56.5T480-720q-33 0-56.5 23.5T400-640q0 33 23.5 56.5T480-560Zm0-80Zm0 400Z"
              /></svg
          ></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'success' %}"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              height="24"
              viewBox="0 -960 960 960"
              width="24"
            >
              <path
                d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h280v80H200Zm440-160-55-58 102-102H360v-80h327L585-622l55-58 200 200-200 200Z"
              /></svg
          ></a>
        </li>
      </ul>
      <div class="dropdown">
        <button
          class="custom-button-with-svg"
          type="button"
          id="dropdownMenuButton"
          aria-haspopup="true"
          aria-expanded="false"
        ></button>
        <div
          class="dropdown-menu"
          style="right: 0; left: auto"
          aria-labelledby="dropdownMenuButton"
        >
          <a class="dropdown-item" href="{% url 'recipes:home' %}">Home</a>
          <a class="dropdown-item" href="{% url 'recipes:recipe' %}">Recipes</a>
          <a class="dropdown-item" href="{% url 'recipes:add' %}">Add Recipe</a>
          <div class="dropdown-divider"></div>
          <a
            class="dropdown-item"
            href="{% url 'recipes:profile' username=request.user.username %}"
            >Profile</a
          >
          <a class="dropdown-item" href="{% url 'success' %}">Logout</a>
        </div>
      </div>
    </nav>
    <!-- End NavBar -->

    <!-- Start of add recipe container -->
    <div class="add-recipe-box">
      <h1>Add a New Recipe</h1>
      <form class="form-container" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row recipe-content">
          <div class="form-group">
            {{ form.name.label_tag }} {{ form.name }}
          </div>
          <div class="form-group">
            {{ form.cooking_time.label_tag }} {{ form.cooking_time }}
          </div>
          <div class="form-group">{{ form.pic.label_tag }} {{ form.pic }}</div>

          <h2>Ingredients</h2>
          <div class="form-group">
            {{ form.ingredients.label_tag }} {{ form.ingredients }}
          </div>
        </div>

        <div class="col button-content">
          <button type="submit">Add Recipe</button>
        </div>
      </form>
    </div>
  </body>
  <script src="{% static 'scripts/add_recipe.js' %}" defer></script>
</html>

recipes/templates/recipes/detail.html
<!DOCTYPE html>

{% load static %}

<html>
  <head>
    <title>TasteBuds</title>
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'styles/detail.css' %}"
    />
  </head>
  <body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand navbar-light bg-light">
      <div class="navbar-brand">
        <a href="{% url 'recipes:home' %}" class="navbar-brand">
          <img src="{{ MEDIA_URL }}new-tastebuds.png" class="logo" alt="Logo" />
        </a>
      </div>

      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recipes:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recipes:recipe' %}">Recipes</a>
        </li>
      </ul>
      <ul class="navbar-nav logout">
        <div class="developer">
          <a
            href="www.jacobcoch.com"
            class="developer-link"
            target="_blank"
            rel="noreferer"
          >
            <img
              src="{{ MEDIA_URL }}developer_icon.gif"
              alt="developer-icon"
              class="developer-icon"
            />
          </a>
        </div>
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'recipes:profile' username=request.user.username %}"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              height="24"
              viewBox="0 -960 960 960"
              width="24"
            >
              <path
                d="M480-480q-66 0-113-47t-47-113q0-66 47-113t113-47q66 0 113 47t47 113q0 66-47 113t-113 47ZM160-160v-112q0-34 17.5-62.5T224-378q62-31 126-46.5T480-440q66 0 130 15.5T736-378q29 15 46.5 43.5T800-272v112H160Zm80-80h480v-32q0-11-5.5-20T700-306q-54-27-109-40.5T480-360q-56 0-111 13.5T260-306q-9 5-14.5 14t-5.5 20v32Zm240-320q33 0 56.5-23.5T560-640q0-33-23.5-56.5T480-720q-33 0-56.5 23.5T400-640q0 33 23.5 56.5T480-560Zm0-80Zm0 400Z"
              /></svg
          ></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'success' %}"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              height="24"
              viewBox="0 -960 960 960"
              width="24"
            >
              <path
                d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h280v80H200Zm440-160-55-58 102-102H360v-80h327L585-622l55-58 200 200-200 200Z"
              /></svg
          ></a>
        </li>
      </ul>
      <div class="dropdown">
        <button
          class="custom-button-with-svg"
          type="button"
          id="dropdownMenuButton"
          aria-haspopup="true"
          aria-expanded="false"
        ></button>
        <div
          class="dropdown-menu"
          style="right: 0; left: auto"
          aria-labelledby="dropdownMenuButton"
        >
          <a class="dropdown-item" href="{% url 'recipes:home' %}">Home</a>
          <a class="dropdown-item" href="{% url 'recipes:recipe' %}">Recipes</a>
          <a class="dropdown-item" href="{% url 'recipes:add' %}">Add Recipe</a>
          <div class="dropdown-divider"></div>
          <a
            class="dropdown-item"
            href="{% url 'recipes:profile' username=request.user.username %}"
            >Profile</a
          >
          <a class="dropdown-item" href="{% url 'success' %}">Logout</a>
        </div>
      </div>
    </nav>
    <div class="main-container">
      <div class="action-buttons">
        {% if request.user == recipe.author %}
        <button
          type="button"
          class="edit-recipe-button"
          data-recipe-id="{{ recipe.id }}"
        >
          Edit Recipe
        </button>
        {% endif %} {% if request.user == recipe.author %}
        <button id="delete-recipe-button">Delete Recipe</button>
        <div id="delete-recipe-modal" class="modal">
          <div class="modal-content">
            <h2>Confirm Deletion</h2>
            <p>Are you sure you want to delete this recipe?</p>
            <form
              class="delete-recipe-form"
              method="post"
              action="{% url 'recipes:delete_recipe' recipe.id %}"
            >
              {% csrf_token %}
              <button id="confirm-delete">Yes, Delete</button>
            </form>
            <button id="cancel-delete">Cancel</button>
          </div>
        </div>
        {% endif %}
      </div>
      <div class="body-and-form-container">
        <div class="body-container">
          <div>
            <img src="{{ recipe.pic.url }}" class="recipe-image" />
          </div>
          <div class="recipe-info">
            <b>Name: </b> {{ recipe.name }}<br />
            <b>Ingredients: </b> {{ recipe.ingredients }}<br />
            <b>Cooking Time: </b> {{ recipe.cooking_time }} (minutes)<br />
            <b>Difficulty: </b> {{ difficulty }}<br />
          </div>
        </div>
        <!-- Edit form (initially hidden) -->
        <form
          method="post"
          action="{% url 'recipes:edit_recipe' recipe.id %}"
          class="edit-recipe-form"
          style="display: none"
        >
          {% csrf_token %}
          <input
            type="text"
            id="edit-recipe-name"
            name="name"
            value="{{ recipe.name }}"
          />
          <input
            type="text"
            id="edit-recipe-ingredients"
            name="ingredients"
            value="{{ recipe.ingredients }}"
          />
          <input
            type="number"
            id="edit-recipe-cooking-time"
            name="cooking_time"
            value="{{ recipe.cooking_time }}"
          />
          <button type="submit">Save Changes</button>
        </form>
      </div>
    </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'scripts/detail.js' %}" defer></script>
</html>

recipes/templates/recipes/profile.html
<!DOCTYPE html>

{% load static %}
<html>
  <head>
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <title>Document</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'styles/profile.css' %}"
    />
  </head>
  <body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand navbar-light bg-light">
      <div class="navbar-brand">
        <a href="{% url 'recipes:home' %}" class="navbar-brand">
          <img src="{{ MEDIA_URL }}new-tastebuds.png" class="logo" alt="Logo" />
        </a>
      </div>

      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recipes:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recipes:recipe' %}">Recipes</a>
        </li>
      </ul>
      <ul class="navbar-nav logout">
        <div class="developer">
          <a
            href="www.jacobcoch.com"
            class="developer-link"
            target="_blank"
            rel="noreferer"
          >
            <img
              src="{{ MEDIA_URL }}developer_icon.gif"
              alt="developer-icon"
              class="developer-icon"
            />
          </a>
        </div>
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'recipes:profile' username=request.user.username %}"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              height="24"
              viewBox="0 -960 960 960"
              width="24"
            >
              <path
                d="M480-480q-66 0-113-47t-47-113q0-66 47-113t113-47q66 0 113 47t47 113q0 66-47 113t-113 47ZM160-160v-112q0-34 17.5-62.5T224-378q62-31 126-46.5T480-440q66 0 130 15.5T736-378q29 15 46.5 43.5T800-272v112H160Zm80-80h480v-32q0-11-5.5-20T700-306q-54-27-109-40.5T480-360q-56 0-111 13.5T260-306q-9 5-14.5 14t-5.5 20v32Zm240-320q33 0 56.5-23.5T560-640q0-33-23.5-56.5T480-720q-33 0-56.5 23.5T400-640q0 33 23.5 56.5T480-560Zm0-80Zm0 400Z"
              /></svg
          ></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'success' %}"
            ><svg
              xmlns="http://www.w3.org/2000/svg"
              height="24"
              viewBox="0 -960 960 960"
              width="24"
            >
              <path
                d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h280v80H200Zm440-160-55-58 102-102H360v-80h327L585-622l55-58 200 200-200 200Z"
              /></svg
          ></a>
        </li>
      </ul>
      <div class="dropdown">
        <button
          class="custom-button-with-svg"
          type="button"
          id="dropdownMenuButton"
          aria-haspopup="true"
          aria-expanded="false"
        ></button>
        <div
          class="dropdown-menu"
          style="right: 0; left: auto"
          aria-labelledby="dropdownMenuButton"
        >
          <a class="dropdown-item" href="{% url 'recipes:home' %}">Home</a>
          <a class="dropdown-item" href="{% url 'recipes:recipe' %}">Recipes</a>
          <a class="dropdown-item" href="{% url 'recipes:add' %}">Add Recipe</a>
          <div class="dropdown-divider"></div>
          <a
            class="dropdown-item"
            href="{% url 'recipes:profile' username=request.user.username %}"
            >Profile</a
          >
          <a class="dropdown-item" href="{% url 'success' %}">Logout</a>
        </div>
      </div>
    </nav>
    <div>
      <div class="profile-header">
        <header>
          <h1>Hello, {{user|title}}</h1>
          <p>Bio: {{user.bio}}</p>
        </header>

        <div class="image-container">
          {% if user.pic %}
          <div class="image-wrapper">
            <img
              src="{{ request.user.pic.url }}"
              alt="Profile Picture"
              class="profile-image"
            />
            <a href="#" id="update-profile-picture" class="update-link"
              >Update Picture</a
            >
          </div>

          <form
            method="post"
            enctype="multipart/form-data"
            id="profile-picture-form"
            action="{% url 'recipes:update_profile_picture' username=request.user.username %}"
          >
            {% csrf_token %}
            <input
              type="file"
              name="profile_pic"
              accept="image/*"
              style="display: none"
              id="file-input"
            />
          </form>
          {% else %}
          <p>No profile picture available.</p>
          {% endif %}
        </div>
      </div>
      <container class="recipe-contents container-md m-auto">
        <div>
          <h2>My Created Recipes</h2>
          <div class="recipe-container">
            {% if created_recipes|length == 0 %}
            <p>No recipes found</p>
            {% endif %} {% for recipe in created_recipes %}
            <div class="recipe">
              <img src="{{ recipe.pic.url }}" width="100" height="100" />
              <h3>{{ recipe.name }}</h3>
              <p>{{ recipe.difficulty }}</p>
              <div class="recipe-buttons">
                <button
                  class="details-button"
                  data-recipe-url="{% url 'recipes:detail' recipe.pk %}"
                >
                  Details
                </button>

                <form>
                  {% csrf_token %}
                  <button
                    class="btn like-button"
                    data-recipe-id="{{ recipe.id }}"
                  >
                    {% if recipe in user.fav_recipes.all %}
                    <i class="fas fa-heart"></i>
                    {% else %}
                    <i class="far fa-heart"></i>
                    {% endif %}
                  </button>
                </form>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        <div>
          <h2>My Favorite Recipes</h2>
          <div class="recipe-container">
            {% if user.fav_recipes.all.count == 0 %}
            <p>No recipes found</p>
            {% else %} {% for recipe in user.fav_recipes.all %}

            <div class="recipe">
              <img src="{{recipe.pic.url}}" width="100" height="100" />
              <h3>{{ recipe.name }}</h3>
              <p>{{ recipe.difficulty }}</p>
              <div class="recipe-buttons">
                <button
                  class="details-button"
                  id="details-button"
                  data-recipe-url="{% url 'recipes:detail' recipe.pk %}"
                >
                  Details
                </button>

                <form id="recipe-fav-form">
                  {% csrf_token %}
                  <button
                    class="btn like-button"
                    data-recipe-id="{{ recipe.id }}"
                  >
                    {% if recipe in user.fav_recipes.all %}
                    <i class="fas fa-heart"></i>
                    {% else %}
                    <i class="far fa-heart"></i>
                    {% endif %}
                  </button>
                </form>
              </div>
            </div>

            {% endfor %} {% endif %}
          </div>
        </div>
      </container>
    </div>
  </body>
  <script
    src="https://kit.fontawesome.com/10833f84d9.js"
    crossorigin="anonymous"
  ></script>
  <script src="{% static 'scripts/profile.js' %}" defer></script>
</html>